apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
  name: attack-pod
  namespace: default
spec:
  containers:
  - image: k8s.gcr.io/redis:e2e
    imagePullPolicy: Always
    name: attack-container
    volumeMounts:
    - mountPath: /root
      name: mount-root-into-mnt
  volumes:
  - name: mount-root-into-mnt
    hostPath:
      path: /
