kind: Pod
apiVersion: v1
metadata:
  name: banana-app
  namespace: fruits-namespace
  labels:
    app: banana
spec:
  containers:
    - name: banana-app
      image: hashicorp/http-echo
      args:
        - "-text=banana"
      resources:
        limits:
          memory: 256Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"

---

kind: Service
apiVersion: v1
metadata:
  name: banana-service
  namespace: fruits-namespace
spec:
  selector:
    app: banana
  ports:
    - port: 5678 # Default port for image
