kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  EphemeralContainers: true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        allow-privileged: "true"
        enable-admission-plugins: NodeRestriction,PodSecurityPolicy
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        anonymous-auth: "false"
        authorization-mode: "Webhook"
        protect-kernel-defaults: "true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-label=worker"
        anonymous-auth: "false"
        authorization-mode: "Webhook"
        protect-kernel-defaults: "true"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-label=worker2"
        anonymous-auth: "false"
        authorization-mode: "Webhook"
        protect-kernel-defaults: "true"
