# Vanilla cluster configuration
# This is a simple cluster with 1 master node and 2 worker nodes
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
