kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  EphemeralContainers: true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        allow-privileged: "true"
        anonymous-auth: "true"
        profiling: "true"
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        anonymous-auth: "true"
        authorization-mode: "AlwaysAllow"
        protect-kernel-defaults: "false"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "my-label2=false"
        anonymous-auth: "true"
        authorization-mode: "AlwaysAllow"
        protect-kernel-defaults: "false"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "my-label3=true"
        anonymous-auth: "true"
        authorization-mode: "AlwaysAllow"
        protect-kernel-defaults: "false"
